### ISSUE TITLE
Hide your IP

### ISSUE THREAD

**Issue by JDiPierro** [CCOSTAN/Home-AssistantConfig#1]
:)

https://github.com/CCOSTAN/Home-AssistantConfig/blob/master/sensor/systemmonitor.yaml#L59

**Comment by CCOSTAN** [comment]
Thanks for that.  Corrected.  Now to delete the history files.

**Comment by JDiPierro** [comment]
Thank you for sharing your config! Just got started with HA and your setup has been super helpful!
