### ISSUE TITLE
Possibly add MQTT DEvice Tracker.

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#102]
Not sure if the payloads should be `home` and `not_home`.  Is this all that's needed?

Kick off payload when we are in bed.  (If we are in Bed, We are HOME.)

Possibly use Foursquare IFTTT -> Maker to kick off Not_home statuses as well. (For me at least).

**Comment by Amir974** [comment]
IFTTT has its own location change action service which you can probably activate

**Comment by CCOSTAN** [comment]
Between the unfi and NMAP tracker, The system is good.  No need to overcomplicate.
