### ISSUE TITLE
Run New Cabling through the house!!

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#103]
- [Respirator](http://amzn.to/2m1uZdT)
- [Tyvek Suit](http://amzn.to/2n8zwgC)
- [500 Feet Coax](http://amzn.to/2mIOn3R)
- [Coax Compression Kit](http://amzn.to/2m1qpfS)
- [Cat 6 Heads](http://amzn.to/2mIM94o)
- [1000 ft Cat 6](http://amzn.to/2n1lbG2)
- [FiberGlass Fishing stick](http://amzn.to/2ngBBpO)

**Comment by rosahas** [comment]
Good luck!   I have Cat 5e.. hopefully that will last for a while.

**Comment by CCOSTAN** [comment]
Definitely NOT doing this myself.  Outsourcing for bids now.

**Comment by CCOSTAN** [comment]
![image](https://user-images.githubusercontent.com/2160436/31550466-67e360d4-afff-11e7-8b0f-56a4ad0de7a1.png)
