### ISSUE TITLE
auto flush PM2 logs when HD capacity hits 80%

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#109]
To flush logs `pm2 flush`

Need to create a shell script automation to kick this off when HD sensor triggers.

**Comment by CCOSTAN** [comment]
Moved everything off of PM2 for now.

**Comment by bestphoneappsdev** [comment]
@CCOSTAN In case you're interested.

If you're using a linux or mac machine & you want to flush your logs every 5 minutes

Then this linux cronjob command could work for you ::

`(crontab -l 2>/dev/null; echo "*/5 * * * * pm2 flush") | crontab -`

**Comment by CCOSTAN** [comment]
Thanks for the code @bestphoneappsdev but I've since switched over to Docker now..
