### ISSUE TITLE
Add Door Sensor to front door.

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#112]
Trigger Guard Dog when opened.

**Comment by CCOSTAN** [comment]
https://github.com/brianjking/homeassistant-config/issues/68

Need to add a `for` to the triggers and then daytime conditions.

2 separate automations..  one without the `for` that triggers immediately (at night) and another that triggers during the day but only after 120 seconds.

Then see if @dale3h can combine them into one nifty Jinja! :)  (can't do jijna for triggers so it might get challenging)

**Comment by dale3h** [comment]
...who says you can't ninja some Jinja for triggers?! ;)

Also, why not use the new `alert` component for this?

**Comment by CCOSTAN** [comment]
I thought you could use dynamic things for triggers since the system kind of defines them at boot up. I'll gladly be wrong though. 

I like the idea of using the new alert component as well.

**Comment by CCOSTAN** [comment]
@dale3h - Do you have an example of Jinja in the triggers?

Otherwise, I think I'll have a 3RD automation the disables/reenables the one I want to use based on time of day.

**Comment by brianjking** [comment]
@dale3h & @CCOSTAN -- Can you take a look and help me out? I'm trying to accomplish the following:

* In HASS UI show specific icons for door open/closed based on state of z-wave door sensor.
* If door is open for longer than 15 seconds send notification via Simplepush alerting me of said door being open.
* In HASS UI display Closed or Opened versus "on" or "off"

Relevant Files:

* https://github.com/brianjking/homeassistant-config/blob/master/automation/front-door-open-alert.yaml
* https://github.com/brianjking/homeassistant-config/blob/master/sensor/front-door-open-closed.yaml

Thank you!

**Comment by brianjking** [comment]
@dale3h & @CCOSTAN -- You can see how this looks in my UI here: https://goo.gl/photos/dkTT8heczPMMtMPBA

Any ideas? I'm beyond lost why this isn't working. :(

**Comment by CCOSTAN** [comment]
@brianjking - The files look good to me.  Does the open/close work in the Template editor?  Maybe it's a case sensitive thing or possibly quotes/no quotes? 

Here is my Door open stuff:
https://github.com/CCOSTAN/Home-AssistantConfig/blob/master/automation/Speech/door_opened.yaml#L6-L11

https://github.com/CCOSTAN/Home-AssistantConfig/blob/master/sensor/devices_states.yaml#L112-L126
