### ISSUE TITLE
Move DB to SQL.

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#116]
https://github.com/brianjking/hass-config/blob/master/docs/mysql.md

Great notes from @brianjKing

**Comment by Amir974** [comment]
Would love to hear the expected benefit of this change and if it paid off!

**Comment by CCOSTAN** [comment]
@Amir974 I'm not sure I am actually going to implement it but the docs were so good, I needed to create a tracking issue. :)

**Comment by brianjking** [comment]
@CCOSTAN @Amir974 -- Thanks, glad you enjoyed the docs.

- MySQL improved the overall speed of the application in my experience.
- Restart/Initial start/stop of HASS is reduced since moving to MySQL from SQLite
- Logbook and history graphs are much faster
- No massive sqlite db files

**Comment by CCOSTAN** [comment]
The space savings might be the one that makes me move to it.   Your Docs make it look so easy! :)

**Comment by brianjking** [comment]
The speed improvement was what made it appealing to me. I'm sure MySQL is far more reliable for the long term than sqlite as well.

**Comment by dale3h** [comment]
@CCOSTAN ...it IS easy. Like, super duper easy. So easy, a caveman could do it.

It was definitely worth the switch for me.

**Comment by CoalaJoe** [comment]
How noticable is it? Can you say percentage?

**Comment by brianjking** [comment]
@coalajoe 5000%, no, I don't have a percentage. I can say that it's faster to start/restart/show history and logbook and seems far more reliable.

**Comment by CoalaJoe** [comment]
@brianjking Thanks

**Comment by Amir974** [comment]
@brianjking I followed this method and I am using the mysql for a couple of weeks now
I have "purge_days: 10" on the config (not sure if that's reasonable / too much)

stop / restart work fine (apparently faster)

**The problem** I see is that often when turning to the LOGBOOK / HISTORY HA seems to think for too long, often NOT producing the screen 
I also get messages in the log at the same time I try to access the log saying:
`ERROR (MainThread) [homeassistant.core] Timer got out of sync. Resetting`

any idea what it means? how I sort it out?

**Comment by CCOSTAN** [comment]
If it ain't broke ...
