### ISSUE TITLE
Change Bolt image to Tesla

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#1168]
https://twitter.com/DomusSapiens/status/1480419404122836992

Easy patch - Need to update the picture. 

https://github.com/CCOSTAN/Home-AssistantConfig/blob/master/config/www/custom_ui/floorplan/images/branding/car.png

https://github.com/CCOSTAN/Home-AssistantConfig/blob/master/config/www/custom_ui/floorplan/images/branding/Bolt_Solar.png

https://github.com/CCOSTAN/Home-AssistantConfig/blob/master/config/www/custom_ui/floorplan/images/branding/bearstone_car.png

**Comment by SaunakNandi** [comment]
Where is the bolt image @CCOSTAN

**Comment by CCOSTAN** [comment]
Not tweeting anymore due to X API closure.
