### ISSUE TITLE
Pi-hole install

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#12]
Add Pi-Hole (Ad blocking) to the network with the Pi Zero. (Add to Home Assistant)

**Comment by skalavala** [comment]
Setting up pi-hole and configuring it in HA is real easy, and I love pi-hole! I'd ask that you check your router first and make sure you can update DNS settings on it. I know of few folks, where they can't modify their router settings as the router was "managed" by the their ISP. I own my modem, and have full access to it, so not a problem for me.

**Comment by CCOSTAN** [comment]
Thanks for the suggestion but I have access to change my DNS settings as well.  I currently use OpenDNS Family Shield DNS settings.   My Big hold up is really getting the Pi Zero networking going. :(
