### ISSUE TITLE
Blink the front lights of the house

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#1217]
A lot of times when I am being driven home, people ask which house is mine.  Let's blink the front lights when I get home so I can just say, the house with the blinking lights.

**Comment by spuljko** [comment]
Or you've had one too much to remember 😃

**Comment by jcallaghan** [comment]
😊 my "Welcome home" notification.
When entering a local zone. Make the notification time sensitive. 
Add actions to the notification that might be helpful when arriving home such as disarm alarm, unlock gate, open garage, flash lights, random scene.
While I've automated disarming the alarm etc etc these can be incredibly helpful for times like you suggested. When we take the dog out for a walk I often hit the random scene to flood the front of house with random colourful light.
The notification is cleared/removed when the one of the external doors is opened.
