### ISSUE TITLE
Investigate Monitoring Solution (Local)

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#1246]
https://github.com/louislam/uptime-kuma?mibextid=uevf24

**Comment by cjramseyer** [comment]
Curious, is this strictly for smarthome monitoring or monitoring in general (i.e. other network devices, home appliances perhaps?)

I found uptime Kuma severely lacked features for a monitoring system, including auto-detect, sensor history, etc.

**Comment by CCOSTAN** [comment]
Closing this one.  Fully set up Pi-Alert and it's working great.
