### ISSUE TITLE
Travis link on frontpage of Readme.md at the bottom

### ISSUE THREAD

**Issue by Trodfoot** [CCOSTAN/Home-AssistantConfig#1259]
After looking at the great documenting and then clicking a link that goes to a deprecated site, figured you can take the few minutes to fix it, if you knew about it.

The link for Travis you have pointing at travis-cli.org and needs to be change to  travis-cli.com
I wouldn't mention it normally but you guys/gals have done a great job on your informations display.

Trodfoot

**Comment by CCOSTAN** [comment]
Thank you very much for making e aware of the error!
