### ISSUE TITLE
Heat map with number of wi-fi connections per Unifi AP

### ISSUE THREAD

**Issue by pgorod** [CCOSTAN/Home-AssistantConfig#1336]
Hi! Just happened to stumble across your repo. Impressive!

Since I noticed you also have Unifi like I do, and you're doing some presence tracking (I'm don't have any of that yet) I was wondering how you would approach the following...

I'm doing Home automation on a facility of a non-profit that I help out with on my free time. They have a bunch of people moving around the premises. They shouldn't control individual presences due to privacy issues, but they would benefit from getting a general idea of "how many people are where".

Do you think it would be possible to get aggregate measures from the Unifi APs, like the connected client count, and show them on a map?

I am a bit of a newbie with HASS and it takes me so long to get the simplest things working, that I fear it would take me ages to get that project up and running. I was kind of hoping some pro like you would find it amusing to play with, and give me a head-start :-)

Thanks any way. Feel free to close the issue if you're not interested.

**Comment by CCOSTAN** [comment]
Unfortunately,  the Unifi integration doesn't give you device counts per AP.  It just gives you basic up /down status and of course lists out all clients across the organization.   

So no way that I know of to list out the number of clients per AP and no way to then plot that on a map.  Sorry. 

![image](https://github.com/CCOSTAN/Home-AssistantConfig/assets/2160436/7275d8fd-e131-4381-9c16-d7ab3faf3121)
