### ISSUE TITLE
Turn off HVAC if window/door is open

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#136]
If open for 3 minutes. 

Then turn back to heat/cool mode when windows/doors are closed. 

Speech notification of course.

**Comment by roystervi** [comment]
- alias: climate Away Mode
  trigger:
    - platform: state
      entity_id: group.family
      from: 'home'
      to: 'not_home'
      for:
        hours: 3
  action:
    - service: climate.set_away_mode
      entity_id: climate.walters
      data:
        mode: 'Away'

    - service: homeassistant.turn_off


I know this is wrong but its the idea am working with

**Comment by Norien** [comment]
urgh.. I need some sort of window sensor so I can play along with you guys.

**Comment by CCOSTAN** [comment]
Got an error.  Must have been a breaking change I missed. 

![image](https://user-images.githubusercontent.com/2160436/71562001-0ea81900-2a4c-11ea-94ad-bfa683581ff9.png)

**Comment by CCOSTAN** [comment]
https://github.com/home-assistant/home-assistant/issues/25721

**Comment by CCOSTAN** [comment]
https://www.vcloudinfo.com/2020/01/save-money-with-home-assistant-and-nest-an-automation-example.html
