### ISSUE TITLE
Migrate IFTTT to Local HA for Phyn

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#1367]
Move all triggers and notifications from IFTTT to local Phyn HACS

**Comment by Hedda** [comment]
I'm interested in moving Phyn from IFTTT to some kind of local integration and following forks + branches by these developers:

* https://github.com/MizterB/homeassistant-phyn
  * https://github.com/MizterB/aiophyn

* https://github.com/rsocko/homeassistant-phyn
  * https://github.com/rsocko/aiophyn

* https://github.com/jordanruthe/homeassistant-phyn
  * https://github.com/jordanruthe/aiophyn

* https://github.com/kasik96/homeassistant-phyn/tree/pc1-support

* https://github.com/timbba80/homeassistant-phyn

* https://github.com/opq8/homeassistant-phyn

Unfortunatly, currently there does not look like there is a single shared upstrea repository where everyone collaborate on all PRs.

**Comment by CCOSTAN** [comment]
Updated to use the shutoff valve as the trigger instead of IFTTT.

**Comment by Hedda** [comment]
@CCOSTAN FYI, I have been using jordanruthe’s fork of homeassistant-phyn for local control and while it has potential to be developered further it at least has been working good for basic controls the last year:

https://github.com/jordanruthe/homeassistant-phyn

**Comment by CCOSTAN** [comment]
Thanks for the Tip @Hedda - This is great to know about.  It has a few extra features like away mode which are nice.  Thanks!
