### ISSUE TITLE
Notification engine question.

### ISSUE THREAD

**Issue by bratanon** [CCOSTAN/Home-AssistantConfig#1388]
I was look at your repo for inspiration and particularly on notifications when I stumbled on this. 
Just by curiosity, this is a typo or does it actually do something undocumented?

https://github.com/CCOSTAN/Home-AssistantConfig/blob/38a854a9611dbe1f6f38f29a82f5a5478c170141/config/script/notify_engine.yaml#L56

I see the same goes for `interuption_level`.
I thought the `true` should be a second param to the `default` filter but this is rendering a list like

```
[
  "information",
  true
] 
```

Thanks for sharing your config.

**Comment by CCOSTAN** [comment]
Hmm.. I used the syntax found here. 
https://tedboy.github.io/jinja2/templ14.html

```
default(value, default_value=u'', boolean=False)
If the value is undefined it will return the passed default value, otherwise the value of the variable:

{{ my_variable|default('my_variable is not defined') }}
This will output the value of my_variable if the variable was defined, otherwise 'my_variable is not defined'. If you want to use default with variables that evaluate to false you have to set the second parameter to true:

{{ ''|default('the string was empty', true) }}

```
