### ISSUE TITLE
Lock status is broken.

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#1466]
Had to roll back to 2024.5.5 since the lock status went from Locked/Unlocked to On\Off.  Should be fixed with 2024.6.3

https://github.com/home-assistant/core/issues/119032

**Comment by CCOSTAN** [comment]
https://youtube.com/shorts/9lDchJDXFwQ

**Comment by jbouwh** [comment]
Should be fixed with: https://github.com/home-assistant/core/pull/119789

**Comment by CCOSTAN** [comment]
Looks like the fix is slated for 2024.7

![image](https://github.com/CCOSTAN/Home-AssistantConfig/assets/2160436/668b3b42-19f4-4cbb-a23b-5b7419db243e)

**Comment by CCOSTAN** [comment]
Confirmed resolved in the latest DEV branch for now as well. 

`image: ghcr.io/home-assistant/home-assistant:dev`
