### ISSUE TITLE
Need to rename the GPIOs to friendly names. 

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#154]
Or just figure out how to reference the friendly name. 

> anyone have an example of grabbing a trigger.entity_id 's friendly name?

**Comment by CCOSTAN** [comment]
https://github.com/CCOSTAN/Home-AssistantConfig/blob/master/automation/Speech/door_opened.yaml#L12

**Comment by Norien** [comment]
Tagging along for future use.

**Comment by CCOSTAN** [comment]
Found it: `trigger.to_state.attributes.friendly_name`
