### ISSUE TITLE
Color CHanging based on Holidays.

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#17]
* Figure out a way to change the color of outdoor lights based on various minor holidays automagically.

**Comment by CCOSTAN** [comment]
https://github.com/CCOSTAN/Home-AssistantConfig/blob/master/script/monthly_colors_scene.yaml

**Comment by CCOSTAN** [comment]
{%- if now().month in [01, 11, 12] -%} Yes {%- else -%} NO {%- endif %}

**Comment by CCOSTAN** [comment]
Code Reference: Interesting way to get National Holidays. 

https://ipsidekick.com/

JSON Sensor.

**Comment by nalipaz** [comment]
I use a Google calendar to define the time-period in which I want a holiday's lights to be set. You could define the rgb colors in the description on the event, I have yet to do that and am simply turning on/off at the moment.
https://github.com/nalipaz/home-assistant-config/blob/master/config/automations/holiday_lighting.yaml

**Comment by Norien** [comment]
not sure if you got this all setup yet 
I have this setup now 
- [Holiday package ( scrape of json file ) set an ```input_select``` to the holiday](https://github.com/Norien/Home-Assistant-Config/blob/master/packages/holiday.yaml#L27-L59)
- [sensor reads the ```input_select``` and outputs rgb code](https://github.com/Norien/Home-Assistant-Config/blob/master/packages/theme.yaml#L92-L120)
- [Use the RGB value in an automation turning on the outdoor lights](https://github.com/Norien/Home-Assistant-Config/blob/master/packages/theme.yaml#L72-L90)

I only have a single bulb now for my outdoor light but I do plan on adding some more down the road. I'm thinking to have a 2nd ```template_sensor``` which would output an ALT colour for use in light zones.
