### ISSUE TITLE
Change logging level for unifi to critical

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#170]
https://community.home-assistant.io/t/unifi-device-tracker-component-ssl-errors/17335

**Comment by CCOSTAN** [comment]
This doesn't seem to fix the issue and the spew is very dangerous to the system so I will be disabling the use of the unifi controller component for now.

**Comment by CCOSTAN** [comment]
https://github.com/CCOSTAN/Home-AssistantConfig/issues/106

**Comment by finish06** [comment]
@CCOSTAN I apologize, I was wrong in my comment.  I had my the logger set at error.  That is what prevented the errors from spewing out....

**Comment by CCOSTAN** [comment]
https://community.home-assistant.io/t/unifi-device-tracker-component-ssl-errors/17335/7
