### ISSUE TITLE
Floorplan card for the nest protects

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#172]
https://github.com/pkozul/ha-floorplan-state-card

**Comment by CCOSTAN** [comment]
https://www.hastebin.com/imolumitop.bash

**Comment by torn8o** [comment]
This moved to another Github location 
https://github.com/pkozul/ha-floorplan

I do have it partially working at the moment

**Comment by CCOSTAN** [comment]
![image](https://user-images.githubusercontent.com/2160436/27111761-5903b138-5080-11e7-8977-ac82cb85f58e.png)

**Comment by CCOSTAN** [comment]
.light_off {
  stroke: black; !important;
  opacity: 0.5;
}
.light_on {

}

**Comment by CCOSTAN** [comment]
![image](https://user-images.githubusercontent.com/2160436/27164669-ca585028-515c-11e7-80b4-8adfc6a28e17.png)

**Comment by CCOSTAN** [comment]
![image](https://user-images.githubusercontent.com/2160436/27166723-b87d8dba-516a-11e7-9d17-5defd6974c2a.png)
