### ISSUE TITLE
Use light sensor to see if TV is left on upstairs. 

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#189]
Will require a bunch of logic. Like making sure lights are off first, that it is nighttime, etc.

**Comment by michaelarnauts** [comment]
There are more reliable ways to do this, depending on the TV.

If your tv has a network connection, you can use a device_tracker or ping sensor to see if it responds. Mine stops replying to ping packets when it's in standby.

You could also connect a RPI to it with HDMI. Depending on the TV, you can read out the status of it trough libcec. If this works fine, you can also turn on the tv and control the volume.

**Comment by CCOSTAN** [comment]
Yeah .. the TV I have upstairs is old.  The kids CONSTANTLY leave it on.  My hope is to build an all in one sensor and IR blaster.  Sense if there is LIGHT from the TV after a certain time (or when we are away) and then fire an OFF command to the TV.

**Comment by skalavala** [comment]
Put a motion sensor in the room, and power the TV using a smart outlet.... when there is no motion detected, turn off the TV :)

**Comment by CCOSTAN** [comment]
https://github.com/1technophile/OpenMQTTGateway
