### ISSUE TITLE
Move zwave controller stick to wink

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#196]
Make the zwave controller stick a secondary controller for wink Wave mesh.

**Comment by CCOSTAN** [comment]
Decided to move all the sensors to the wink which has been preforming like a champ.

**Comment by DoTorr** [comment]
Which Wink hub do you have?  I have a wink hub 1 and in general the response times are too long.  I was about to move all devices to HASSIO with aeotec zwave stick.

**Comment by CCOSTAN** [comment]
I have the Wink 1. Most of the lights attached to it are outside landscaping so response time is not an issue for me.  (https://youtu.be/ylPzQ0s7zxc)

**Comment by CCOSTAN** [comment]
> Which Wink hub do you have? I have a wink hub 1 and in general the response times are too long. I was about to move all devices to HASSIO with aeotec zwave stick.

Are you running the ZWave stick on a Pi? or Docker based image? (I know HassIO IS docker but curious if you are running HASSIO on the Pi or running on another configuration?) // @DoTorr

**Comment by DoTorr** [comment]
I have HassIO on a Docker container running on a HP micro PC with Ubuntu Server.

**Comment by CCOSTAN** [comment]
@DoTorr Can you share the code to pass the stick into the container?

**Comment by DoTorr** [comment]
Just looked through my notes and it looks like I didn't have major problems setting it up.  

I used the Integrations method as described here:

https://www.home-assistant.io/docs/z-wave/installation/

My configuration.yaml has the following entry:
zwave:
usb_path: /dev/ttyACM0

The other two links I have on my notes are:

https://www.home-assistant.io/docs/z-wave/

https://www.home-assistant.io/hassio/zwave/

Let me know if this worked or not.  I can dig in a little more later if you need more help.
