### ISSUE TITLE
pool control

### ISSUE THREAD

**Issue by mvillarejo** [CCOSTAN/Home-AssistantConfig#254]
First of all, great work. Thanks for sharing.

You seem to have a pool, did you manage to control the different pieces from HASS?

Thanks

**Comment by CCOSTAN** [comment]
Thanks @mvillarejo! I haven't really messed with the pool control yet.  #191 & #248 are the only items I have been thinking of. 

Neither really has anything to do with Hass. :)

**Comment by CCOSTAN** [comment]
https://www.reddit.com/r/homeassistant/comments/8p0qdm/add_your_pool_to_home_assistant_for_20_with/?st=JI42IS0M&sh=6c0f1975
