### ISSUE TITLE
Revisit Network Monitor. Online/Offline status.

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#285]
Leverage something like the Battery scripts to cycle through EVERYTHING that might be offline and notify and tweet about it.

**Comment by philhawthorne** [comment]
Could you use normal Home Assistant device trackers for this?

https://philhawthorne.com/using-home-assistant-device-trackers-to-watch-the-critical-components-of-your-smart-home/

**Comment by CCOSTAN** [comment]
It'll work but I don't want to create sensors for everything like I am doing now.  I want to create a Jinja loop that will just grab stuff in a domain and then monitor it.

**Comment by CCOSTAN** [comment]
One line Jinja from @dale3h - 
```Offline Devices: {{ dict((states|selectattr('entity_id', 'in', state_attr('group.network_devices', 'entity_id'))|list)|groupby('state'))['offline']|map(attribute='name')|list|join(', ') }}```
