### ISSUE TITLE
Set up grafana

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#293]
https://philhawthorne.com/getting-started-with-grafana-influxdb-for-home-assistant/

cc: @philhawthorne

**Comment by Norien** [comment]
Tagging along for this one as it's on my to-do list

**Comment by CCOSTAN** [comment]
https://community.home-assistant.io/t/complete-guide-on-setting-up-grafana-influxdb-with-home-assistant-using-official-docker-images/42860
cc: @arsaboo

**Comment by CCOSTAN** [comment]
More docker info : https://github.com/brianhanifin/docker-compose-config/blob/7bd645dbc9dc3721012f3d577aa74694e7d8510d/docker-compose.yaml#L20-L53
from @brianhanifin

**Comment by CCOSTAN** [comment]
![image](https://user-images.githubusercontent.com/2160436/41202765-9c7fcd24-6c9b-11e8-836e-3d6112242797.png)
