### ISSUE TITLE
Investigate adding Node-red to HA setup.

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#305]
Use Node Red docker Container to see if there is some more enhanced things I can do with HA.

**Comment by Bodge-IT** [comment]
Looking forward to seeing what you do with this. I'm already offloading Ha with something's that can just be done easier and better in NR. There's a lot if cross over though deciding where to run what is tricky

**Comment by disrupted** [comment]
@Bodge-IT how's your experience so far regarding the performance of NodeRED?

**Comment by Bodge-IT** [comment]
Performance?  I.e time to react to input?  I've always found it pretty good.  It's the maintnence of the nodes that both gives NodeRed its power and is its weakness at the same time, that and documentation.  Most of the Node authors don't write any.
I haven't figured out how I'm going to use it with HA yet properly.  I don't think it's as simple as "get node-red to do all the automations;' as there's so much overlap in capability.

**Comment by CCOSTAN** [comment]
Sticking with Straight HA Yaml for now.  It REALLY does everything I need it to do.
