### ISSUE TITLE
Move to MariaDB

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#341]
#116 - I REALLY want to get @dale3h new code for the solar output working on HA so I'm gonna spin up a MariaDB onhis recommendation.

good notes here : https://mschuetz.org/posts/use-mariadb-for-homeassistant/

**Comment by CCOSTAN** [comment]
```
sensor:
  - platform: sql
    db_url: !secret recorder_db_url
    queries:
      - name: "Solar 24h"
        column: 'solar_kwh'
        unit_of_measurement: 'kWh'
        query: >-
          SELECT ROUND(SUM(solar_kwh), 2) AS solar_kwh
          FROM (
            SELECT AVG(state) AS solar_kwh
            FROM states
            WHERE entity_id = 'sensor.solar_now'
            AND state != 'unknown'
            AND last_updated >= DATE_SUB(UTC_TIMESTAMP(), INTERVAL 24 HOUR)
            GROUP BY HOUR(last_updated)
          ) AS total_kwh;
```

**Comment by disrupted** [comment]
are there any advantages of MariaDB over something like InfluxDB? don’t know much about this but many seem to stick to influx..

**Comment by CCOSTAN** [comment]
I'm not sure.  I mainly added this to support the code above by @dale3h.  He recommended MariaDB to me specifically so I'm just taking his recommendation.

**Comment by snjoetw** [comment]
@disrupted I don't think you can use influx as recorder based on this: https://www.home-assistant.io/components/recorder/

**Comment by disrupted** [comment]
@snjoetw oh you can, in fact that's what I am using right now. https://www.home-assistant.io/components/influxdb/

**Comment by snjoetw** [comment]
That's what I'm using too but I don't think it can be used as "recorder" in configuration.yaml . Although I've never tried but according to the doc, influxdb is not in the supported list

Were you able to set the recorder to use influxdb?

**Comment by disrupted** [comment]
@snjoetw uhh no, haven’t bothered with this since I purge the internal recorder entirely every week.

**Comment by CCOSTAN** [comment]
All migrated to InfluxDB.
