### ISSUE TITLE
Travis

### ISSUE THREAD

**Issue by mf-social** [CCOSTAN/Home-AssistantConfig#348]
When you moved your repo around a bit so you have a 'landing page' and then your config in a folder you stopped getting travis verified merges.

I don't know whether you're bothered, but if you are I think you can get them back by moving the `.travis.yml` out in to the same folder as your landing page, and changing the script line to

```
script: hass -c config/ --script check_config
```

Which will point it at the files in the directory (the dot in it currently means 'this folder').  Travis will only run if the yml file is in the main directory for the repo AFAIK.

I think 🤔 

I didn't submit a PR because it might need a bit of tweaking and I don't actually know whether you're happy for it not to do the checks at the minute.

If you do start using it again I'll chuck a PR in that will tidy away the need for the fake SSL files for you 👍

**Comment by CCOSTAN** [comment]
No idea how to get this configuration to pass. :(

**Comment by mf-social** [comment]
Don't merge 349, but leave it open, let me mess around with it a bit and get it working fully 👍

**Comment by CCOSTAN** [comment]
Sounds good.  Thanks for the assist @mf-social.

**Comment by mf-social** [comment]
Should now be fixed in #349
