### ISSUE TITLE
Work on self-heal package.. 

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#355]
https://github.com/technicalpickles/picklehome/issues/62

First up - Check Sun state every 15 minutes and turn off exterior lights if they are on.

**Comment by sfouchek** [comment]
I know this issue is closed, but when I look at your self-heal.yaml, all it seems to do is send out a tweet. I am really interested in how you might go about restarting the fire tablet and kick off a zwave heal. Can you help me with what action and other bits would do those two things above?
