### ISSUE TITLE
Alternative light_check() macro

### ISSUE THREAD

**Issue by brianhanifin** [CCOSTAN/Home-AssistantConfig#358]
I thought you'd appreciate seeing this. While I haven't gotten the speech logic working properly on my setup yet, I had a need to create a sensor that held the list of lights that are currently on. I saw the opportunity to simplify the light_check() macro logic, so I thought I'd share. Here's a sneak peek:

```
 {%- macro light_check() -%}
  {% if states.group.all_lights.state != 'off' -%}
    There are
    {%- set lights_on_count = sensor.lights_on_friendly|length + 1 -%}
    {%- if lights_on_count == 1 -%}
      The {{ sensor.lights_on_friendly }} is the only light on right now.
    {%- else -%}
      There are {{ lights_on_count }} lights on right now.
      The {{ sensor.lights_on_friendly }} are on.
    {%- endif -%}
  {%- endif -%}
{%- endmacro -%}
```

https://gist.github.com/brianhanifin/1f9436c7b6c28917c9be02605b6cff74

https://github.com/CCOSTAN/Home-AssistantConfig/blob/40f8fd2edc80a0ac27f618c62873588ba8e01a64/config/script/speech_engine.yaml#L78

**Comment by CCOSTAN** [comment]
Thanks for that addition!  I just updated my files!
