### ISSUE TITLE
Rock @dshokouhi 's Neato Custom Component.

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#384]
https://github.com/dshokouhi/hass-neato-custom-component

cc: @dshokouhi

**Comment by dshokouhi** [comment]
@CCOSTAN just a heads up but had someone point out last night that a few import statements needed to be updated.  I went ahead and fixed that so things should be working 100% now.

https://github.com/dshokouhi/hass-neato-custom-component/issues/1
