### ISSUE TITLE
Install Whole House Energy Meter

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#39]
Ordered via new egg - $18 bucks. 

https://community.home-assistant.io/t/aeon-labs-home-energy-meter-polling-interval-issue/1944/4

**Comment by CCOSTAN** [comment]
Going to need jOE TO COME BY AND HELP WITH THIS INSTALL.

**Comment by robbiet480** [comment]
@CCOSTAN such anger for jOE

**Comment by CCOSTAN** [comment]
Haha. :)

**Comment by CCOSTAN** [comment]
Might add to the pool equipment instead.  less risk of killing myself.  (

**Comment by CCOSTAN** [comment]
This most likely will be solved with the New Tesla Power wall coming in. 

Maybe I'll bug the Electrician to put my sensor in as well.  -< Yeah.. This is what I am going to do.

**Comment by CCOSTAN** [comment]
Just not needed now with the Powerwall.  I get all the data I need from it.
