### ISSUE TITLE
Create Lightning alarm

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#392]
When lightning is near, TTS a warning. 

https://community.home-assistant.io/t/my-little-accuweather-com-minutecast/54564

cc: @swetoast

**Comment by JamesMcCarthy79** [comment]
This would go off all the time at my place.



Sent from my Samsung Mobile on the Telstra Mobile Network


-------- Original message --------

**Comment by CCOSTAN** [comment]
https://community.home-assistant.io/t/lightning-strikes-nearby/54047/12

Keep an eye on that.

**Comment by CCOSTAN** [comment]
https://github.com/home-assistant/home-assistant/pull/25001

Looks like it is here with 0.96! Awesome!

**Comment by CCOSTAN** [comment]
https://www.home-assistant.io/integrations/geo_location/

Another good component option.

**Comment by thejeffreystone** [comment]
Heads up... WWLLN is no more. 
home-assistant/core#35926

I think I will have to go with a hardware solution in the backyard. I haven't found any other good options.

**Comment by CCOSTAN** [comment]
Looks like this should be an easy install via HACS. 

https://github.com/mrk-its/homeassistant-blitzortung

**Comment by CCOSTAN** [comment]
Still need to do : 

- [ ] Add in Twitter Images
- [ ] Add in VARIABLES (need a good rainstorm to inspect the data provided. 
- [ ] Possibly use new 'Chooser' to send different notifications based on home or not. (Maybe Use Zones or just Home not_Home)

**Comment by CCOSTAN** [comment]
https://www.vcloudinfo.com/2020/08/adding-a-lightning-sensor-to-home-assistant.html
