### ISSUE TITLE
eclipse-mosquitto no manifest

### ISSUE THREAD

**Issue by vvallee** [CCOSTAN/Home-AssistantConfig#412]
Attempting to install, and getting.

ERROR: no matching manifest for unknown in the manifest list entries

`root@k8s:/home/pi/docker# /usr/local/bin/docker-compose up
WARNING: The Docker Engine you're using is running in swarm mode.

Compose does not use swarm mode to deploy services to multiple nodes in a swarm. All containers will be scheduled on the current node.

To deploy your application across the swarm, use "docker stack deploy".

Pulling mqtt (eclipse-mosquitto:latest)...
latest: Pulling from library/eclipse-mosquitto
ERROR: no matching manifest for unknown in the manifest list entries`

**Comment by vvallee** [comment]
seems to be ok when setting eclipse-mosquitto:1.4.4 instead of latest.

**Comment by CCOSTAN** [comment]
Thanks for the Heads Up!
