### ISSUE TITLE
Tesla Powerwall 2 Link 404

### ISSUE THREAD

**Issue by IanDuncanT** [CCOSTAN/Home-AssistantConfig#423]
Link for the Tesla Powerwall 2 in the README.md results in a 404. I don't know where it should go to so I can't submit a pull request yet.

**Comment by IanDuncanT** [comment]
Most shortened links are down.

**Comment by CCOSTAN** [comment]
Thanks for the report.  I recently made a domain name switch.  I thought I had forwarding all set up but apparently not. :(   All links on the repo have been updated.  Thanks again for letting me know!

**Comment by IanDuncanT** [comment]
You also have links on vCloudInfo.com going to VMwareInfo.com Just make sure to check those. (One of them is on the Tesla Powerwall Wall page)

**Comment by CCOSTAN** [comment]
Yeah .. those are so much trickier to switch out.. I am working with Godaddy to fix the forwards.. but if you need the info, you can just manually swap that url in.  Thanks again for the reports..

**Comment by CCOSTAN** [comment]
Updated all short links.  Looks like GoDaddy did NOT like forwarding paths (since June 2018) .. so a quick domain transfer to Google.DOMAINS and we are all good again!  Thanks again!
