### ISSUE TITLE
Add in Grid Status via Powerwall.

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#429]
https://github.com/stbenjam/home-assistant-config/blob/master/config/configuration.yaml?fbclid=IwAR1ey2oL--IF_zvuSDa8hWgFI7oNe1C2YFtojd4jv1c3EL0ao5wFsWYWRl0#L501

cc: @stbenjam

**Comment by CCOSTAN** [comment]
https://youtu.be/KHaLddx5wPg

**Comment by stbenjam** [comment]
Is that youtube video available publicly?

BTW, I added a hack-y sensor to estimate daily home usage by sampling the instantaneous load values over time.  Still a work in progress, I haven't compared to Tesla app values yet but I imagine it should be close

https://github.com/stbenjam/home-assistant-config/blob/master/config/packages/solar.yaml#L239-L256

**Comment by CCOSTAN** [comment]
Tomorrow : 10:30Am EST. 

I will totally try out that new code! Thanks! And thanks for this code.

**Comment by CCOSTAN** [comment]
@stbenjam Is the new code dependent on the SolarEdge invertors you have?  I only have crappy deltas that give ZERO information.  But if you are getting daily totals from your powerwalls, that would be a really welcome addition. (pun intended). 

:)

**Comment by stbenjam** [comment]
It works based on the Powerwall's API only. However, it doesn't work correctly, numbers aren't close to Tesla, so either there's a arithmetic error, or I need to sample more frequently than every 120 seconds.
