### ISSUE TITLE
Add in Github Sensor

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#453]
Great piece of sensor code by @SilvrrGIT

https://github.com/SilvrrGIT/HomeAssistant/issues/98

**Comment by CCOSTAN** [comment]
Convert to official GitHub Sensor (possibly - depending on what is returned)

https://www.home-assistant.io/components/sensor.github/

**Comment by SilvrrGIT** [comment]
Looks like someone made a custom card also

https://github.com/ljmerza/github-card
