### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by SilvrrGIT** [CCOSTAN/Home-AssistantConfig#465]
Im guessing this is supposed to be Ubiquiti.

https://github.com/CCOSTAN/Home-AssistantConfig/blob/871981dd706e35d45a5c1a84ffc67e34cfc468db/config/packages/pihole.yaml#L130

https://github.com/CCOSTAN/Home-AssistantConfig/blob/871981dd706e35d45a5c1a84ffc67e34cfc468db/config/customize/device_tracker.yaml#L108

**Comment by CCOSTAN** [comment]
Thanks for the Heads Up @SilvrrGIT  - This will be in the next video coming out. :)

**Comment by CCOSTAN** [comment]
https://www.youtube.com/watch?v=FDNMslmaHZs
