### ISSUE TITLE
Set up Pi Hole on Docker

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#472]
Run two pi-holes on the network in the typical DNS load balanced fashion.
I would run one on a physical Pi Zero and the other in a docker container.  The first would be the primary DNS and single DHCP for the network.  It would also have a less aggressive set of lists for blocking and would be used for most of the user devices on the network (phones, laptops, etc…) while the second could have a much more aggressive set of blocking rules that I would point only Smart Home devices to.  Since they are less likely to need to get to most websites (or ANY), I could be extremely aggressive on the blocking.  Also since that Pi-Hole would be on the docker image, it would have more horsepower and could handle a larger block list.  I would then just hardcode that Pi-hole address into the DNS sections of the IOT devices.

**Comment by asa79** [comment]
If its only for Smart Home Devices, maybe setting up Whitelist might be easier then a large blacklist.  Just means everything is blocked expect for the addresses allowed.  This will use less processing power on the pihole as well

**Comment by CCOSTAN** [comment]
That's a Great Idea @aaronargent! Maybe I'll flip flop the idea then.  Have the DHCP and IOT whitelist on the weaker Pi Zero and the Block list on a Docker VM.

**Comment by CCOSTAN** [comment]
Raspian 9 is no longer supported.  Time to move the Pi to Docker for easy updating.

**Comment by CCOSTAN** [comment]
So the Raspberry Pi died..  Brought up a new PiHole on Docker now.   This will make things a LOT easier and easier to backup now.
