### ISSUE TITLE
Typo in Powerwall package

### ISSUE THREAD

**Issue by Lanerra** [CCOSTAN/Home-AssistantConfig#474]
Noticed a typo in the powerwall.yaml file on lines 119 and 121; "sensor.grid_statuse"

Reference
https://github.com/CCOSTAN/Home-AssistantConfig/blob/ccb98cb0943732a05385d783a21f77a1baf0b790/config/packages/powerwall.yaml#L119

https://github.com/CCOSTAN/Home-AssistantConfig/blob/ccb98cb0943732a05385d783a21f77a1baf0b790/config/packages/powerwall.yaml#L121

**Comment by CCOSTAN** [comment]
Thank you so much for that @Lanerra ! Let me go fix that.
