### ISSUE TITLE
Skybell light color...

### ISSUE THREAD

**Issue by MYeager1967** [CCOSTAN/Home-AssistantConfig#475]
Did you happen to figure out how to change the Skybell light color using Homeassistant?

**Comment by CCOSTAN** [comment]
Hey @MYeager1967 - The Skybell just shows up with a light.  Be sure to add this in : 
https://github.com/CCOSTAN/Home-AssistantConfig/blob/master/config/packages/skybellhd.yaml#L46-L47

Then I just change it like normal.  I really only have it as part of my Holiday theming script.. 
https://github.com/CCOSTAN/Home-AssistantConfig/blob/master/config/scene/monthly_colors.yaml#L33-L36

You can see it in this video (in the early part)
https://youtu.be/ylPzQ0s7zxc
