### ISSUE TITLE
Change Tuya plugs to Tasmota

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#481]
Now that you can do it over the air, I'm in.

https://github.com/ct-Open-Source/tuya-convert

**Comment by dshanske** [comment]
I just ordered a few to try. Tell me how it goes

**Comment by CCOSTAN** [comment]
I'll try to make a video (https://www.youtube.com/vcloudinfo) and see if I can flash these things : https://amzn.to/2B7rux8

**Comment by CCOSTAN** [comment]
I think this can be done on my Home Assistant Laptop using a docker container.  Gonna try that.

**Comment by CCOSTAN** [comment]
> I think this can be done on my Home Assistant Laptop using a docker container. Gonna try that.

This is not gonna work.  I think I need to bring back the PI

**Comment by pinkywafer** [comment]
If you're running proxmox on a machine with 2 network interfaces, there's a container. See https://github.com/whiskerz007/proxmox_tuya-convert_container

**Comment by CCOSTAN** [comment]
Thanks Jenny, That's the issue for me.  My Laptop only has the single interface but I do have a Pi on the shelf with a Wifi and hard line connection.  I need to just buckle down and set that up.

**Comment by CCOSTAN** [comment]
Decided to just use the home Assistant approved Tuya Developed Integration now instead.
