### ISSUE TITLE
Using !secret in tempting engine 

### ISSUE THREAD

**Issue by Chariyski** [CCOSTAN/Home-AssistantConfig#55]
Hi @CCOSTAN,

Great job with the entire HA config 👍 

I was looking the configuration and found that you are using !secret in templating ( https://github.com/CCOSTAN/Home-AssistantConfig/blob/master/sensor/systemmonitor.yaml#L61 )

On my side, that is not working and there is a feature request for that ( https://community.home-assistant.io/t/make-secrets-available-in-templating-engine/10507 ). 

Is your code really working or it is false positive :)

**Comment by CCOSTAN** [comment]
Thanks. :)

It is definitely passing the config checker. If you are right it is NOT working. The ipchange sensor is reporting true when it should be false. I hadn't noticed. Unfortunately I don't want my ip exposed so I'll leave it broken until there is a proper work around. 

Thanks
Carlo.

**Comment by CCOSTAN** [comment]
I took @happyleaves advice and just hid the entire IPChange sensor.  I did leave commented/scrubbed versions exposed for others though.

Thanks for bringing this to my atttention! @Chariyski

**Comment by Chariyski** [comment]
Supper 👍

**Comment by Chariyski** [comment]
A silly question... 

I just added
```
sensor 2:
  platform: template
  sensors:
    ipchange:
      entity_id: sensor.external_ip
      value_template: "{%- if is_state('sensor.external_ip', 'secret') -%} False {%- else -%} True {%- endif %}"
```
to my secret file, but it is not working. Is there something different that need to be done for secret files?

**Comment by CCOSTAN** [comment]
No worries. You don't need to add it to your secret.yaml file.  You can just add it to your sensor files and then update your .gitignore file. 

https://github.com/CCOSTAN/Home-AssistantConfig/blob/master/.gitignore#L21

**Comment by Chariyski** [comment]
Even better. Thanks.
