### ISSUE TITLE
Replace MuxiMux

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#574]
Replace MuxiMux with a Home Assistant Page (for applications).

Best to keep everything in the Home Assistant page for a Bunch of reasons.

**Comment by djryan012** [comment]
Do you mind elaborating. Are you planing on using i-panels instead?

**Comment by CCOSTAN** [comment]
@djryan012 My thought is to either have iPanels or maybe even just static links on the lovelace page.  I really just need jump pages to various things when I am home.. so HA seems like a logical place to store them

**Comment by CCOSTAN** [comment]
Dashy is perfect for this .. No reason to move it to Home Assistant. 

![image](https://github.com/CCOSTAN/Home-AssistantConfig/assets/2160436/64122b2c-b3ae-4286-9679-c443e0fc1a19)
