### ISSUE TITLE
Update monthly Color holidays

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#575]
Use @brianhanifin 's code 
https://github.com/brianhanifin/Home-Assistant-Config/blob/master/components/sensors/datetime/firstdayofsummer.yaml?fbclid=IwAR3zx0NzaR06zLmztD21pMJkYWKiXG_xzkXPofJCR2md0139COFNGM2k-KI

to potentially smarten up my dates for those floating holidays that I have to hard code every year.

**Comment by CCOSTAN** [comment]
5{{ get_nth_dayofmonth(2, "Sunday", 5).split('-')[2].split(' ')[0]}} =Mother's day for instance.

**Comment by brianhanifin** [comment]
Now you've made me want to smarten up the code. Do you have a good reference for holiday rules?

Here are my files for reference. I added a `PERSONAL` section to my holidays.json file with the idea that lights could be changed for family birthdays and anniversaries.

- [/json_data/holidays.json](https://github.com/brianhanifin/Home-Assistant-Config/blob/master/json_data/holidays.json)
- [/components/sensors/datetime/flag.yaml](https://github.com/brianhanifin/Home-Assistant-Config/blob/master/components/sensors/datetime/flag.yaml)
- [/components/sensors/datetime/holiday.yaml](https://github.com/brianhanifin/Home-Assistant-Config/blob/master/components/sensors/datetime/holiday.yaml)
- [/components/sensors/datetime/holiday_scene.yaml](https://github.com/brianhanifin/Home-Assistant-Config/blob/master/components/sensors/datetime/holiday_scene.yaml)
- [/scripts/lights/holiday_color_change.yaml](https://github.com/brianhanifin/Home-Assistant-Config/blob/master/scripts/lights/holiday_color_change.yaml)
- [/scripts/lights/holiday_sensors_update.yaml](https://github.com/brianhanifin/Home-Assistant-Config/blob/master/scripts/lights/holiday_sensors_update.yaml)

**Comment by CCOSTAN** [comment]
So far, I think it's just the 8 dynamic holidays.  I was just going to look them up individually in Wikipedia and then write the code.

**Comment by brianhanifin** [comment]
I've stared compiling rule notes using google searches "how to calculate president's day" for example.

**Dynamic Holiday Rules**

Martin Luther King Day
3, Monday, 1  

President's Day 
3, Monday, 2  

Easter Sunday 
* TBD

Mother's Day
2, Sunday, 5

Memorial Day
 last, Monday, 5

**Comment by CCOSTAN** [comment]
thanks @brianhanifin !  I have to P2V hyper-V servers right now.. Ugh.. work is getting in the way of my Home Automation desires at the moment. :)

BTW: Last monday is a hard one to code no?

**Comment by brianhanifin** [comment]
It shouldn't be too hard. I will add that ability to the macro in a bit.

**Comment by brianhanifin** [comment]
I completed the list of dynamic holidays above.

Easter looks to be very tricky to nail down. If we can find someone else's function to determine easter I might be able to convert it to a macro. However, it may need to continue to be manually entered. But, if we can get rid of the rest of the manual entry that would be huge!

**Comment by CCOSTAN** [comment]
agreed.  We can just use a JSON for easter..   Here are the next 20 years. 

2020April 12th
2021April 4th
2022April 17th
2023April 9th
2024March 31st
2025April 20th
2026April 5th
2027March 28th
2028April 16th
2029April 1st
2030April 21st
2031April 13th
2032March 28th
2033April 17th
2034April 9th
2035March 25th
2036April 13th
2037April 5th
2038April 25th
2039April 10th
2040April 1

**Comment by brianhanifin** [comment]
3 hours later....

With this version we can replace the number (1, 2, 3, or 4) with "last". `{{ get_nth_dayofmonth("last", "Monday", 5, 2020) }}` determines memorial day next of year. I developed this code in the template editor (copy and paste the code below to see the result). I'm going to leave implementation for another day as my brain is cooked for the day. :)

```
{%- macro dayofweek_number(dayofweek) -%}
  {%- if dayofweek == "Sunday" or dayofweek == "Sun" -%}
    1
  {%- elif dayofweek == "Monday" or dayofweek == "Mon" -%}
    2
  {%- elif dayofweek == "Tuesday" or dayofweek == "Tue" -%}
    3
  {%- elif dayofweek == "Wednesday" or dayofweek == "Wed" -%}
    4
  {%- elif dayofweek == "Thursday" or dayofweek == "Thu" -%}
    5
  {%- elif dayofweek == "Friday" or dayofweek == "Fri" -%}
    6
  {%- elif dayofweek == "Saturday" or dayofweek == "Sat" -%}
    7
  {%- endif -%}
{%- endmacro -%}

{%- macro lastdayofmonth(month, year) -%}
  {%- set daysinmonths = [31,28,31,30,31,30,31,31,30,31,30,31] -%}
  {%- set month = month|int -%}
  {%- set year = year|int -%}

  {# Simplified leap year calculation. See https://www.mathsisfun.com/leap-years.html #}
  {%- set isleapyear = year % 4 == 0 and (year % 100 != 0 or year % 400 == 0) -%}

  {%- set monthindex = month-1 -%}
  {%- if month == 2 and isleapyear -%}
    {{ daysinmonths[monthindex]+1 }}
  {%- else -%}
    {{ daysinmonths[monthindex] }}
  {%- endif -%}
{%- endmacro -%}

{#
ex. Get the nth Wendnesday of June.
1st: {{ get_nth_dayofmonth(1, "Wednesday", 6) }}
2nd: {{ get_nth_dayofmonth(2, "Wednesday", 6, 2019) }}
3rd: {{ get_nth_dayofmonth(3, "Wednesday", 6) }}

Reference: https://www.bennadel.com/blog/1446-getting-the-nth-occurrence-of-a-day-of-the-week-for-a-given-month.htm
#}
{%- macro get_nth_dayofmonth(nth, dayofweek, month, year=now().strftime('%Y')) -%}
  {%- set dayofweek = dayofweek_number(dayofweek)|int -%}
  {%- set firstdateofmonth = strptime(year ~'-'~ month ~'-1', "%Y-%m-%d") -%}
  {%- set firstdayofmonth = dayofweek_number(firstdateofmonth.strftime('%A'))|int -%}

  {# Determine the first occurrence of the day. #}
  {%- if firstdayofmonth < dayofweek -%}
    {%- set firstoccurrence = (dayofweek - dayofweek_number(firstdayofmonth)) -%}
  {%- else -%}
    {%- set firstoccurrence = (7 - firstdayofmonth + dayofweek) + 1 -%}
  {%- endif -%}

  {%- if nth is number -%}
    {# Determine the nth occurrence of the dayofweek. #}
    {%- set nthoccurrence = firstoccurrence + 7 * (nth-1) -%}
  {%- else -%}
    {#
    Determine the LAST occurrence of the dayofweek.

    Reference: https://cflib.org/udf/GetLastOccOfDayInMonth
    #}
    {%- set lastdayofmonth = lastdayofmonth(month, year)|int -%}
    {%- set lastdayname = strptime(year ~'-'~ month ~'-'~ lastdayofmonth, "%Y-%m-%d").strftime('%A') -%}
    {%- set lastdaynumber = dayofweek_number(lastdayname)|int -%}
    {%- set daydifference = lastdaynumber - dayofweek -%}

    {# Add a week if the result is negative. #}
    {%- if daydifference < 0 -%}
      {%- set daydifference = daydifference + 7 -%}
    {%- endif -%}

    {%- set nthoccurrence = lastdayofmonth - daydifference -%}
  {%- endif -%}

  {# Return the day with the month and year so it can be useful. #}
  {{ strptime(year ~'-'~ month ~'-'~ nthoccurrence, "%Y-%m-%d") }}
{%- endmacro -%}


{{ get_nth_dayofmonth("last", "Monday", 5, 2020) }}
```

**Comment by brianhanifin** [comment]
On facebook you said:

> The next step is to figure out the best way to implement it. I'm thinking of a YAML package with individual holiday sensors (mother, father, labor day, etc..) and then reference them in the month script.

Instead of individual holidays, we could create a single next holiday date sensor.  In theory this could be set on startup and not updated until that day after that date! Nice, simple, and efficient.

**Comment by CCOSTAN** [comment]
How about using the new Days Until Sensor logic?  This should work no matter how complicated the holiday is.  #288

**Comment by brianhanifin** [comment]
I had to step away from the code. It was making smoke come out of my ears. ;)

That is an interesting bit of code... if it works, especially the command line. I will leave this in my inbox to revisit hopefully soon.

**Comment by CCOSTAN** [comment]
I have a video coming out on the DAYS uNTIL SENSOR.  Once that's off my plate, I'll see if I can get it working with the Holiday colors.  I have High Hopes! :)

**Comment by brianhanifin** [comment]
I've also considered using the [Anniversaries](https://github.com/pinkywafer/Anniversaries) Custom Component by @pinkeywafer. Which is fine for static events like birthdays and anniversaries, but I doubt we'd be able to populate a dynamic number of sensors (like easter).

**Comment by pinkywafer** [comment]
Somewhere I've got a calculation for Easter. ... there's no reason why I couldn't add it and other holidays to the anniversaries sensor if this would be a good idea

**Comment by CCOSTAN** [comment]
@pinkywafer Would it be worth leveraging WolfRam rather than doing the calculation locally? (depending on how hard some of the calculations are (First night of passover for instance would be a tough one I think). ).

http://products.wolframalpha.com/api/libraries.html

**Comment by pinkywafer** [comment]
@CCOSTAN I'm not sure about Passover, I've never tried to work it out! But Easter is actually not too difficult (although long winded!). But the sensor could be set to only update once a day anyway,  so thatd eliminate any regular processing

**Comment by CCOSTAN** [comment]
@pinkywafer Passover was just the first one I thought of. :) Here's my current list of moving holidays. 

https://github.com/CCOSTAN/Home-AssistantConfig/blob/master/config/json_data/holidays.json#L27-L116

**Comment by pinkywafer** [comment]
Nice list!!!  Thing is though, things such as 'last Wednesday in the month' type is not too bad, and the Christian holidays are based from Easter, so there's really only 1 calculation!

**Comment by CCOSTAN** [comment]
I just realized @brianhanifin has the rules already up here : https://github.com/CCOSTAN/Home-AssistantConfig/issues/575#issuecomment-507842887

**Comment by pinkywafer** [comment]
Just a thought.. There are many public APIs for public holidays, maybe an easier solution would be a sensor based on one of those?

**Comment by CCOSTAN** [comment]
@pinkywafer - Surprisingly I wasn't able to find any.  almost all (actually ALL that I found) were pay services.  Apparently knowing holidays is super lucrative in the financial space (payroll, etc)..

**Comment by CCOSTAN** [comment]
We are using one for flag days though.. 
https://github.com/CCOSTAN/Home-AssistantConfig/blob/master/config/packages/holiday.yaml#L48-L60

**Comment by pinkywafer** [comment]
https://calendarific.com will give 1000 api calls a month on the free tier

**Comment by CCOSTAN** [comment]
That 's SOOOOO perfect!  I think when I was looking in the past, once I saw Pricing on the webpage, i bounced to the next one in the list. :)

**Comment by pinkywafer** [comment]
I've now made a calendarific integration. https://github.com/pinkywafer/Calendarific
Just waiting for the PR to be merged which will add it as a default in HACS!

**Comment by CCOSTAN** [comment]
Now I just need to install HACS and then make a video on this most awesome of components!  Thanks for letting me know @pinkywafer !

**Comment by brianhanifin** [comment]
@CCOSTAN so... have you seen [the list of holidays](https://calendarific.com/holidays/2019/US)? It begs the question: what color will your lights be on **International Programmers' Day**? :)

**Comment by CCOSTAN** [comment]
Come a long way since #17
