### ISSUE TITLE
Make Bear Stone Norris Sensor

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#578]
https://api.chucknorris.io/jokes/random?name=Bear%20Stone&category=dev

**Comment by CCOSTAN** [comment]
https://github.com/CCOSTAN/Home-AssistantConfig/commit/5ef97985b1f35ac800be0e05c3ad919e47eae31c

**Comment by atomicpapa** [comment]
lol
