### ISSUE TITLE
Build rest sensor for rocket launches. 

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#59]
https://launchlibrary.net/docs/1.2.1/api.html

Because I live in Florida and this would be fun for Joanna to tell us about and also flash lights.  And maybe color the front different too. Or maybe just DURING THE LAUNCH!!  that would be neat!

**Comment by PhyberApex** [comment]
What is it you need help with here?

**Comment by CCOSTAN** [comment]
The site in the top provides the information via json.  I just haven't gotten around to building a sensor to parse all the data.  It's nothing specific to my house so I added the Help Wanted label there.  Ideally, I would want the sensor to have the date of the next Orlando launch.

**Comment by phillprice** [comment]
I wonder if this would help as the link above appears dead - not sure if temporary. 
https://ipeer.auron.co.uk/launchschedule/api/1/launches/
