### ISSUE TITLE
Disable Comments

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#618]
I don't think they offer enough value to offset the site slowness. 

Communications and discussion can happen on Social Media Platforms. 

Critical information can be added and updated on the blog post itself.

**Comment by Bodge-IT** [comment]
I find it quite irritating when unable to comment.  You might mitigate that by creating a clear link to the forum where comments would be?

**Comment by CCOSTAN** [comment]
I'm Juggling the reality of Speed of the site vs commenting.  Currently, My posts get at best 1 or 2 comments every dozen or so Posts.  I have about 850 blog posts on the site and only about 200 comments in total.  I get way more engagement on this Github and on the YouTube channel.  I have all of my social accounts on the right side of the blog for discussion..  (although that might not be apparent).    I appreciate the perspective though @Bodge-IT

**Comment by Bodge-IT** [comment]
Just sayin.  Your priorities are your own. Just shining a light through the user's eyes, from their perspective to "engage" with you, it's a trip to another site, possibly registering to boot.  Most users will already be following and already registered there, but users are also getting a little numb to "registering" and may just drop off at that point.  Perfect opp for A/B test?

**Comment by CCOSTAN** [comment]
@Bodge-IT Totally and I appreciate the insight.  There are a few issues I am tackling.. for instance, fractured conversations.  Conversations, here, on youtube, normal social media (Twitter (@ccostan) is my favorite BTW) and then the blog.  The blog is by far the least used.   From a data standpoint, people just aren't using that commenting system so I'm sacrificing it for improved Loading speeds.   In general I would prefer to have most/all of the Smart Home Conversations on GitHub and YouTube and then Tech conversations on Twitter.   I, of course, could add that tagline into the posts  (I push comments for guests for instance to their twitter accounts). 

I just disabled them now and will see how/if anyone notices.  Hopefully, there are enough outlets in Social to continue to answer questions, etc.. most of the conversations on the Blog have just been direct reader to me anyway.  Very few, if any, reader to reader.

I feel like this would have been a harder decision that I wouldn't have made if there were actual comments. :)  Right now, there just wasn't any use for it.   I recognize that it will affect some users like yourself but hopefully, you will still reach out to me on the other channels. 

interesting note on the existing comments: it was running DISQUS which did require another registration which COULD have been hindering the comments all along.   If/When I bring back comments, I will probably test out Facebook or Native WordPress comments.

**Comment by Bodge-IT** [comment]
Yeah, was also wondering if a simpler system that just required email might also have been option.

**Comment by CCOSTAN** [comment]
This definitely requires a bit more thought.   I really think removing DISQUS was the right call in this situation but thanks to @Bodge-IT 's comments, I want to reevaluate using WP commenting system.  I agree that it is useful to be able to engage right on the site while/after reading the post. 

I'm closing the issue since I disabled DISQUS but feel free to continue to comment here to continue to discuss (or twitter! :) ) .  It's quite useful for me to hash these things out with other perspectives.
