### ISSUE TITLE
Jinja Code.py

### ISSUE THREAD

**Issue by torn8o** [CCOSTAN/Home-AssistantConfig#64]
looks like there are spacing issues when it contains icon: entry other wise code it awesome
```light.aeotec_dsc27103_micro_dimmer_2nd_edition_level_8_0:
  friendly_name: 'Master Bedroom Fan'icon: mdi:lightbulb
  emulated_hue: False
  hidden: False

**Comment by CCOSTAN** [comment]
I'm on mobile now but look for the dash near the {%. That willl remove the white space.  Delete the dash. 

And thanks!

**Comment by CCOSTAN** [comment]
Yeah. I have it fixed in the top block. 
  {{-'icon: Is wrong. 

I normally just use the top block and just change the domain on top from sensors to light to script etc.

**Comment by torn8o** [comment]
I fixed it just letting you know for the other people that may miss it. otherwise still awesome
