### ISSUE TITLE
Install HACS

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#647]
Somehow I didn't have this on my List!! 

https://hacs.netlify.com/

**Comment by CCOSTAN** [comment]
https://www.youtube.com/watch?v=DsTqOlrQQ1k

**Comment by CCOSTAN** [comment]
https://www.youtube.com/watch?v=4cOdgW23KCA

**Comment by CCOSTAN** [comment]
https://youtu.be/4cOdgW23KCA

**Comment by pinkywafer** [comment]
Try: https://youtu.be/7HXFaD_ZLec

**Comment by CCOSTAN** [comment]
I think I am going to tackle this now. :) Thanks for the Video Link @pinkywafer!
