### ISSUE TITLE
Polly currently Broken with 0.100

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#666]
After #664, Polly TTS broke.

Details here: https://github.com/home-assistant/home-assistant/issues/27418

The house is super quiet and the kids have no idea who is supposed to do chores. :)

**Comment by CCOSTAN** [comment]
Issue #666 - Seems appropriate.

**Comment by CCOSTAN** [comment]
Rolled back to 0.99.3 for now until a fix is released.

**Comment by thejeffreystone** [comment]
Glad I watch other repos! Holding off on upgrade.

**Comment by Spirituss** [comment]
Doesn't work for me too.
