### ISSUE TITLE
Freeze Warning

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#676]
https://github.com/thejeffreystone/home-assistant-configuration/commit/013b3e063517a1634252b4b962f8496100b056f3

Similar to the #392 Lighting alert. 

Add freeze warning to daily speech.

**Comment by thejeffreystone** [comment]
After putting this out there and letting it run I'm going change up the turn off automation. Instead of turning it off in the middle of the night I will set the turn off automation to trigger anytime the temp rises above freezing as long as the forecasted temp is also above freezing.

**Comment by CCOSTAN** [comment]
![image](https://user-images.githubusercontent.com/2160436/83955852-7e090c80-a825-11ea-8a41-4ee9e280956a.png)

Other possible ways to predict freeze issues.

**Comment by CCOSTAN** [comment]
![image](https://user-images.githubusercontent.com/2160436/83956003-0c31c280-a827-11ea-811f-7a56c99f2534.png)
