### ISSUE TITLE
Split out watchdog automations

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#70]
No reason to have huge files.  start breaking them all out.

**Comment by CiquattroFPV** [comment]
for the light watchdog you need to change the trigger.entityid to: 
{{ trigger.to_state.attributes.friendly_name }}

**Comment by CCOSTAN** [comment]
Are you sure? This seems to be working in my environment.   I use trigger.entityid in a lot of automations.

**Comment by CiquattroFPV** [comment]
ohh you are right.. it work.. my fault.. I was using it in a wrong way  :-)
