### ISSUE TITLE
Add additional Protection for RGB LED strips.

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#71]
The controllers kept getting dampish.. :(  Hopefully this cheap electrical box will provide enough protection to keep it running. 

![image](https://cloud.githubusercontent.com/assets/2160436/23146471/0e221436-f7a5-11e6-86cf-072338c9ba13.png)

![image](https://cloud.githubusercontent.com/assets/2160436/23146478/1ca566c0-f7a5-11e6-8d47-ecc65f133185.png)

Part list: 
* [LED RGB Wifi Controller - flux_led compatible](http://amzn.to/2jUBSBE) with [LED Strip kits](http://amzn.to/2gJYfZ5) - ~100 Feet. These are great [Power supplies](http://amzn.to/2j5Vu0D) - [Outdoor Housing](http://amzn.to/2m2dG0X) - Finished Product #71

**Comment by rosahas** [comment]
Are you using NodeMCU chip to drive these lights like Bruh Automation, or just via flux_led?

**Comment by CCOSTAN** [comment]
@rosahas no. I'm just using the RGB controller linked above and the flux_led component. Works right out of the box without anything complex.  For this project I just wanted a cheap RGB accent lighting for outside my house

**Comment by nalipaz** [comment]
You could easily fill the holes the wires are exiting with some all-purpose caulk for a water-tight seal. It should fairly easily peel off when need. Alternatively use hot glue as it will peel even easier, although it is not as good against weather when expanding/contracting from what I know.

**Comment by CCOSTAN** [comment]
@nalipaz Yeah.. It's pretty well covered from the elements so I was thinking about just a tape based shield on the openings.  They are a pretty good size (about 1" diameter).  I'll snap a picture when it is all completed.

**Comment by nalipaz** [comment]
So as to not use too much caulk, you can stuff the hole with a Styrofoam packing peanut or similar and then caulk, would be a pretty thin layer of caulk and easy to do in a few minutes. But yeah, it doesn't seem like much will get in there as it is.

**Comment by CCOSTAN** [comment]
The peanut idea is excellent actually.  I want to prevent insects from taking up room and board in there as well.  Great Suggestion!

**Comment by Vasiley** [comment]
CCOSTAN go to electrical store and ask for duck seal ....can get cheaper for smaller amounts http://www.homedepot.com/p/Ideal-1-lb-Block-Duct-Seal-Compound-Standard-Pack-6-Blocks-31-601/300496860?cm_mmc=Shopping%7cTHD%7cG%7c0%7cG-VF-PLA-D27E-Electrical%7c&gclid=EAIaIQobChMI3OOjm4ee1gIVh1mGCh0jmQWVEAQYASABEgLFr_D_BwE&gclsrc=aw.ds&dclid=CISAp56HntYCFcwSgQodny8GiQ
