### ISSUE TITLE
hide_if_away warning on startup

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#719]
Seems to be a bug that should work itself out in one of the versions to come. 

https://github.com/home-assistant/home-assistant/issues/31549

**Comment by pinkywafer** [comment]
hide_if_away is being depreciated.  You need to remove it from known_devices.yaml.  Sadly new devices discovered are still adding it to known_devices.yaml at the moment

**Comment by CCOSTAN** [comment]
> hide_if_away is being depreciated. You need to remove it from known_devices.yaml. Sadly new devices discovered are still adding it to known_devices.yaml at the moment

Yeah .. I can't find it at all.  I linked an open case above where it looks like there is a bug that will hopefully be fixed in future versions before full deprecation.

**Comment by pinkywafer** [comment]
I've just found it in the legacy device tracker. I might see about fixing it if I get chance!!

**Comment by CCOSTAN** [comment]
No longer in my logs.  Seems to have resolved itself with the HA updates.
