### ISSUE TITLE
Implement Travis for config validation

### ISSUE THREAD

**Issue by robbiet480** [CCOSTAN/Home-AssistantConfig#73]
@tradiuz recently got Travis CI working to validate configuration upon pushing to GitHub. It's quite simple, just sign up for a free Travis-CI.org account and [follow these instructions](https://github.com/home-assistant/home-assistant.github.io/pull/2103).

You have the most popular maintained configuration in the `home-assistant-config` topic on GitHub now so I think i'm going to "require" (quotes because it would be appreciated if you could implement) this one for you since we are going to start announcing this as best practice for public configs.

**Comment by tradiuz** [comment]
If you need any assistance, I'll gladly help out, since I found it hugely helpful.

**Comment by Chariyski** [comment]
What is the status of your build?
Mine failed :( - https://travis-ci.org/Chariyski/Home-Assistant-Configuration/builds/203940571

**Comment by robbiet480** [comment]
@Chariyski Looks like you have a secret that should have been an integer but is actually a string.

**Comment by robbiet480** [comment]
@Chariyski Actually other way around, you may have provided an int when it was expecting a string

**Comment by CCOSTAN** [comment]
@Chariyski  - All Good now! 
![image](https://cloud.githubusercontent.com/assets/2160436/23183173/2339e9d0-f849-11e6-8deb-3b17d72996a2.png)

Thanks for the suggestion and help everyone.

**Comment by Chariyski** [comment]
Thanks from me, too.

Mine is green, too 👍

**Comment by brianjking** [comment]
I want to add-in a webhook to `git pull` whenever new commits are pushed to my repo and the Travis-CI build reports back a successful build with `The command "hass -c . --script check_config" exited with 0.` After that I'd want to run `sudo systemctl restart home-assistant.service`

Any tips? BTW - Here's my repo: https://github.com/brianjking/hass-config

**Comment by CCOSTAN** [comment]
None from me @brianjking.  I pretty much only PUSH up to github.  I have never had to do a pull.  I'm work from Home so I pretty much only code when I am next to the Pi. 

Side note: Do you love your 3d printer?  I think I want one now.

**Comment by robbiet480** [comment]
@brianjking you'd want to watch for the `status` webhook that GitHub will send you once Travis updates the status. [Here's](https://developer.github.com/v3/activity/events/types/#statusevent) the GitHub docs on that.

**Comment by brianjking** [comment]
@CCOSTAN My Pi is headless with the occasional use of a VNC connection. I do my editing from either my Mac, Linux or Windows machine, push to GitHub, GitHub webhooks to Travis-CI, if Travis-CI says all is well then I'll `ssh` to the Pi and `git pull`.
