### ISSUE TITLE
BREAKING CHANGE: COLOR_NAME

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#744]
Change all Color_name to rgb codes. 

https://flaviocopes.com/rgb-color-codes/

```bash
[homeassistant.components.light.reproduce_state] The use of other attributes than device state attributes is deprecated and will be removed in a future release. Invalid attributes are ['color_name']. Read the logs for further details: https://www.home-assistant.io/integrations/scene/

```

**Comment by CCOSTAN** [comment]
https://www.w3schools.com/colors/colors_picker.asp?color=00bfff

Useful in the search and replace.

**Comment by jcallaghan** [comment]
@CCOSTAN would [light profiles](https://www.home-assistant.io/integrations/light/) work as a replacement for this for you?

> light_profiles.csv in the current working directory. Light profiles define an xy color and a brightness. If a profile is given and a brightness then the profile brightness will be overwritten.

**Comment by CCOSTAN** [comment]
> @CCOSTAN would [light profiles](https://www.home-assistant.io/integrations/light/) work as a replacement for this for you?
> 
> > light_profiles.csv in the current working directory. Light profiles define an xy color and a brightness. If a profile is given and a brightness then the profile brightness will be overwritten.

Thanks for the suggestion @jcallaghan but I think moving everything to the RGB values was a worthwhile experiment.  I still have the minor issue with the templates but by the time the color_name is deprecated, I hope they will have had time to sort that out.

**Comment by CCOSTAN** [comment]
Apparently this will only affect SCENES which is ok.  Won't affect my template issue.. 

https://github.com/CCOSTAN/Home-AssistantConfig/blob/24dea5c4690518156251af80cc0fdc3bc9ac5a82/config/automation/late_night_outside_helper.yaml#L51-L61
