### ISSUE TITLE
What kind of installation are you using?

### ISSUE THREAD

**Issue by aureliosaraiva** [CCOSTAN/Home-AssistantConfig#751]
Hi, how are you? What kind of installation are you using? Are you using Hassio, supervisor or manual installation?

**Comment by CCOSTAN** [comment]
I am using Home Assistant Core running on Docker. 
https://www.vcloudinfo.com/2018/02/journey-to-docker.html

**Comment by CCOSTAN** [comment]
Update!  Apparently I am running Home Assistant Container! :) 
https://www.home-assistant.io/blog/2020/05/26/installation-methods-and-community-guides-wiki/
