### ISSUE TITLE
Eventually Migrate off DarkSky

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#753]
The API is shutting down at the end of 2021.

Need to migrate off eventually. 

https://github.com/matt8707/hass-config/issues/11

**Comment by CCOSTAN** [comment]
Looks like I need to replace these sensors:
```yaml
- dark_sky_precip
- dark_sky_precip_intensity
- dark_sky_precip_intensity_max
- dark_sky_cloud_coverage
- dark_sky_tempature
- dark_sky_wind_speed
- dark_sky_minutely_summary
- dark_sky_uv_index
- dark_sky_humidity
```
cc: https://github.com/pinkywafer/Home-Assistant_Config/issues/10#issuecomment-665831729

**Comment by CCOSTAN** [comment]
Potential: https://github.com/r-renato/ha-climacell-weather

**Comment by CCOSTAN** [comment]
AccuWeather seems good as well - 
https://www.home-assistant.io/integrations/accuweather/

**Comment by pinkywafer** [comment]
I've just set up AccuWeather to try also... Always used to use the AccuWeather mobile app and found it to be one of the better weather apps

**Comment by pinkywafer** [comment]
We'll... That's a lot of data!
![Screenshot_2020-08-12-23-37-53-36_c3a231c25ed346e59462e84656a70e50.jpg](https://user-images.githubusercontent.com/8636233/90075334-04920c80-dcf5-11ea-851c-88ec0ed1228d.jpg)

**Comment by CCOSTAN** [comment]
Oh My!!  98 sensors!  Going to really have to tweak the `HISTORY` and `RECORDER` settings for that. :)

**Comment by CCOSTAN** [comment]
This one is done.  COmpletely migrated off to Pirate Weather and it's awesome.
