### ISSUE TITLE
Convert groups of Lights to Light Groups

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#764]
Convert my Groups of lights to light groups for use with Alexa and HomeKit.

Should enable dimming and other light features. 

related: #380

**Comment by CCOSTAN** [comment]
![image](https://user-images.githubusercontent.com/2160436/83953865-15646480-a812-11ea-9df0-accbec423573.png)

Be sure to delete all Alexa entries and rediscover.

**Comment by CCOSTAN** [comment]
![image](https://user-images.githubusercontent.com/2160436/83953880-375de700-a812-11ea-9884-66c4e5b979ac.png)

**Comment by jcallaghan** [comment]
Having to create some light groups on the back of my move to ZHA. Would you happen to know if you can have a light group in another light group (or have lights referenced in multiple light groups)?
