### ISSUE TITLE
Move the Github POST from IFTTT to Local

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#773]
https://github.com/jcallaghan/home-assistant-config/issues/103

#606

**Comment by jcallaghan** [comment]
What are you posting to GitHub? I was considering raising a bug if a sensor is offline for an extended period, maintenance task to replace low batteries and when an update is detected.

**Comment by CCOSTAN** [comment]
I use ti for automatic issues on HA upgrades and I love the idea of raising an issue for an offline entity or battery replacement. 

I was having an issue setting it up on the github side though..   Might need to teams you for some air support to resolve it.

**Comment by jcallaghan** [comment]
Hit me up anytime buddy. Make sure you add "Bearer token-id" as your secret. This caught me out which is why I also added a demo secrets file to emphasise this.

**Comment by CCOSTAN** [comment]
https://github.com/jcallaghan/home-assistant-config/blob/master/entities/rest/new_github_issue.yaml

**Comment by CCOSTAN** [comment]
![image](https://user-images.githubusercontent.com/2160436/94347649-034a4400-0004-11eb-81d3-102f4ee8cd7e.png)
