### ISSUE TITLE
Figure out number of automations triggered 

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#784]
https://twitter.com/syralist_ha/status/1273737253802651656?s=21

**Comment by jcallaghan** [comment]
Perhaps this might give you some ideas? 

![image](https://user-images.githubusercontent.com/7449908/85380162-81460d00-b534-11ea-8520-71ff05651d8c.png)

**Comment by CCOSTAN** [comment]
https://twitter.com/home_assistant/status/1275501822178848768

**Comment by CCOSTAN** [comment]
Would have been interesting but not worth the trouble.   It would be VERY tricky to figure out a filter to stop the Counter Automation from triggering itself over and over in a looping fashion. 

https://twitter.com/home_assistant/status/1275841786544443393
