### ISSUE TITLE
Updater not Updating. 

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#796]

**Comment by CCOSTAN** [comment]
https://github.com/home-assistant/core/issues/33142

**Comment by CCOSTAN** [comment]
```yaml
    - service: homeassistant.update_entity  #Look for a new Home Assistant Version
      entity_id: binary_sensor.updater
```

**Comment by pinkywafer** [comment]
I tried the `homeassistant.update_entity` approach, but it did not work, so changed approach altogether
FYI I'm also adding notifications for addons, supervisor and UI updates! code should be on github in a short while.
https://github.com/pinkywafer/Home-Assistant_Config/issues/9

**Comment by CCOSTAN** [comment]
That'll be neat Jenny.. Thanks for linking the issue.  I'll keep an eye out for the Code.  Tag me if you remember. 

Thanks!

**Comment by pinkywafer** [comment]
* [My addons update sensors and notification](https://github.com/pinkywafer/Home-Assistant_Config/blob/master/packages/system/addon_versions.yaml)
* [My Home assistant version sensors + notifications](https://github.com/pinkywafer/Home-Assistant_Config/blob/master/packages/system/homeassistant_version.yaml)
* [My OS update notification + sensor (relies on my home assistant available version sensor above)](https://github.com/pinkywafer/Home-Assistant_Config/blob/master/packages/system/homeassistant_os_update.yaml)
* [My Supervisor update sensor + automation](https://github.com/pinkywafer/Home-Assistant_Config/blob/master/packages/system/supervisor_updates.yaml)
* [My HACS components notifications (+ hacs config!)](https://github.com/pinkywafer/Home-Assistant_Config/blob/master/packages/system/hacs.yaml)

I created these drawing inspiration from various others, and I'm struggling to remember them all!!
The github issue (I've only set one up for Home assistant, not supervisor, addons OS or HACS as their config is not stored on github) is one issue I have created manually.  The automation re-opens the issue and comments the version available.  I then close the issue when I commit the .HA_VERSION file.  It should then be re-opened by HA when the next update is available

**Comment by CCOSTAN** [comment]
Update using the `VERSION` integration. 
https://www.home-assistant.io/integrations/version/

**Comment by CCOSTAN** [comment]
This just doesn't seem necessary anymore.
