### ISSUE TITLE
Use GitHub Webhooks to Notify HA 

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#813]
Using WebHooks in GitHub, you can alert HA to do different things 

For me, tweet when a new issue or Commit is made. (THROTTLED OF COURSE) 

https://github.com/CCOSTAN/Home-AssistantConfig/settings/hooks

Can get rid of IFTTT with this.

**Comment by pinkywafer** [comment]
I'm going to have to 'borrow' this!

**Comment by CCOSTAN** [comment]
Ha!  You have PLENTY of Bear Stone Credit with your last PR.  Borrow Away!  :)
Plus there's a GREAT chance you might get this implemented before me. .haha and then I can borrow from you!

**Comment by pinkywafer** [comment]
have a look at:
https://github.com/pinkywafer/Home-Assistant_Config/blob/master/packages/github/github_webhook.yaml

it's happily sending to my discord!

**Comment by CCOSTAN** [comment]
@pinkywafer - Does the following condition work for you?
```yaml
      - condition: template
        value_template: >-
          {%- if trigger.json.action == "created" or "closed" or "opened" or "reopened" %}
            True
          {%- else -%}
            False
          {%- endif -%}
```
It seems to still let things through that are "edited" or "labelled".  Is that happening to you? You can edit an issue title to reproduce it. 
Thanks

**Comment by CCOSTAN** [comment]
As an example : 
https://twitter.com/BearStoneHA/status/1309904776629563394

**Comment by BeardedTinker** [comment]
That's true, I'll try to add your fix as editing title did go through! Thanks for this one!

**Comment by CCOSTAN** [comment]
Unfortunately, still not working for me @BeardedTinker.  Will have to figure out another way to keep the spam down.

**Comment by CCOSTAN** [comment]
@pinkywafer , @BeardedTinker  Fixed with this code. 

https://github.com/CCOSTAN/Home-AssistantConfig/commit/c2145a6e258f2bf5ec5f3f71e3769e50acbf8cee#diff-1ac31087b886dcb8a09abc76d1ca8e76R69-R70

**Comment by pinkywafer** [comment]
Yes, it is letting other things through. I haven't looked further into it yet though

**Comment by BeardedTinker** [comment]
That's a neat trick and looks like it stopped events that are not listed!

**Comment by pinkywafer** [comment]
Yes, the or was evaluating each string after or as a separate condition ie, it existed so was true...
The X==y or X==z approach would have worked also, but using ```in[y, z]``` is much neater
