### ISSUE TITLE
Add in ID to all Automations - Help Wanted!

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#814]
Using this UUID generator from @Frenck
https://www.uuidgenerator.net/

This will be a LONG term project as I Touch all automation in the systems. (There are a lot)

If you want to practice submitting PRs, this is a great way for you to practice contributions to GitHub.  Just find an Automation in my repo and add in an ID using the Generator above and add it below the alias. 
```yaml
- alias: 'People Greeting'
  id: 29c5c9dd-550a-4761-a224-78cdc3dd9f43
```
Today UUIDs, tomorrow Integrations!  :) 
Thanks!

**Comment by jcallaghan** [comment]
Don't forget this for your favourite code editor https://twitter.com/jamescallaghan/status/1285177437014433793 ;)
