### ISSUE TITLE
create ID for automation

### ISSUE THREAD

**Issue by ranrinc** [CCOSTAN/Home-AssistantConfig#825]
How did you create the ID? is there an ID generator somewhere? thanks

**Comment by CCOSTAN** [comment]
https://www.uuidgenerator.net/

**Comment by ranrinc** [comment]
thank you....

**Comment by sunsgs** [comment]
Why are u adding IDs to each automation?

**Comment by CCOSTAN** [comment]
I've read that this is a preferred practice now.  Helps with the sorting and displaying of connections within the LoveLace UI. 

![image](https://user-images.githubusercontent.com/2160436/92028297-cc994a80-ed31-11ea-9f6f-928738f022b2.png)
