### ISSUE TITLE
device tracker

### ISSUE THREAD

**Issue by sunsgs** [CCOSTAN/Home-AssistantConfig#868]
Are u using nmap as a solo tracker on ios?
I Am using only the app on two iphone but it seems that on my wife iphone that doesn't use the app often, the home / not home is not working pretty well

**Comment by CCOSTAN** [comment]
I use both the Home Assistant iOS App and NMAP. 

![image](https://user-images.githubusercontent.com/2160436/92160011-57df1280-edfc-11ea-8ec4-bf8a31ab698d.png)

**Comment by sunsgs** [comment]
I have to study NMAP. Did not understand how it works and how to configure it.
Do I need to track each iphone ip?

**Comment by CCOSTAN** [comment]
I'm probably moving away from it though and going to use my Unifi and Home Assistant Mobile app as the mechanism.  
With the new Persons thing though, you can stack a lot of different presence stuff into one bucket. 

#756 & #105

**Comment by CCOSTAN** [comment]
> Do I need to track each iphone ip?

Works via MAC.  So you have to make sure you turn off MAC randomization on the new iPhones for your wifi as well.
