### ISSUE TITLE
Fridge Watcher

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#869]
Write some automations for the BLINK Cameras ( https://amzn.to/3lOYTCv ) to monitor the Fridge temps and alert me if it goes above 42F

**Comment by doune** [comment]
Which one did you choose for your fridge ?
How it works ?
Do you have some pictures to share ?

Le ven. 4 sept. 2020 à 18:06, Carlo Costanzo <notifications@github.com> a
écrit :

**Comment by CCOSTAN** [comment]
I have a Beta one that I can't really take a picture of .. but it's Battery operated and sits in the fridge and takes 60 second videos of me when I open the fridge. :) 

But more importantly, adds all the sensors to Home Assistant for me to query.  (My fridge is on the fritz - LG [https://amzn.to/2QSAYUv] so I'm using the Camera temps to monitor the fridge temps since I don't trust it 100% yet. )

![image](https://user-images.githubusercontent.com/2160436/92267438-ad73f780-eeae-11ea-8b47-1a6f8d6485ce.png)

If I have to deploy more, I will choose something more cost-effective like the Shelly (https://amzn.to/35acMFl)
