### ISSUE TITLE
IFTTT is Closing it's doors on me.

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#872]
Need to move stuff off of IFTTT and probably move into Alexa Routines.

**Comment by CCOSTAN** [comment]
![image](https://user-images.githubusercontent.com/2160436/93927525-ffa67c80-fce6-11ea-9c80-0f96528e98d5.png)

**Comment by CCOSTAN** [comment]
![image](https://user-images.githubusercontent.com/2160436/94346416-7fd82500-fffa-11ea-81ee-cefbae9b147a.png)

**Comment by CCOSTAN** [comment]
![image](https://user-images.githubusercontent.com/2160436/94349603-fafa0500-0013-11eb-8f30-ff62d3e1bb78.png)

**Comment by pinkywafer** [comment]
I must admit i actually quite enjoyed closing my ifttt account the other day... Although i hadn't been using it much before

**Comment by CCOSTAN** [comment]
All IFTTT has been migrated/ Decommissioned.
