### ISSUE TITLE
Cuckoo Clock

### ISSUE THREAD

**Issue by ranrinc** [CCOSTAN/Home-AssistantConfig#879]
Hi there,

Been using your cuckoo clock automation for a long time however after 115 It not working as it should be. It seems to hit by the hours and 3 minutes later it will hit again. Maybe you have a solution? Thanks

**Comment by CCOSTAN** [comment]
Hey @ranrinc - Thanks for bringing this to my attention.  I am having this issue as well.  Will post updates as I figure it out.. seems like a bug though.

**Comment by CCOSTAN** [comment]
https://github.com/home-assistant/core/issues/40365

**Comment by pinkywafer** [comment]
Shouldn't your time pattern be:
Minutes: 0
(Or minutes: 30(
Without hours being in the config?

**Comment by CCOSTAN** [comment]
> Shouldn't your time pattern be:
> Minutes: 0
> (Or minutes: 30(
> Without hours being in the config?

Gonna give this a go.  I don't think it will fix the error since it's 3 minutes after (which is weird) but maybe and it's definitely the right way to write the yaml so worth the change regardless.

**Comment by CCOSTAN** [comment]
https://github.com/CCOSTAN/Home-AssistantConfig/commit/9a87c534161c2bc761df7d16945062c5ebabd891

**Comment by CCOSTAN** [comment]
I think it might only be reading in the first digit from the trigger (so 3 instead of 30) since I noticed that it is not triggering on the 30.  So as a test I am changing the second trigger to 50 to see if it triggers on the hour and then 5 minutes later this time.

**Comment by CCOSTAN** [comment]
Confirmed.  It triggered once at 0 and once at 5 (instead of 50). 
![image](https://user-images.githubusercontent.com/2160436/93721021-42d3e480-fb5b-11ea-8d37-defa50af2d1b.png)

**Comment by CCOSTAN** [comment]
Looks like removing the quotes solved the issue.

**Comment by CCOSTAN** [comment]
https://www.vcloudinfo.com/2017/11/building-digital-cuckoo-clock-with-home.html

**Comment by pinkywafer** [comment]
note that it should work with quotes again in 0.115.3 ref: https://github.com/home-assistant/core/pull/40470

**Comment by ranrinc** [comment]
Yay.. thanks you guys...
