### ISSUE TITLE
Trigger data no longer translating

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#895]
Does anyone have any ideas why this trigger data no longer works? 

https://github.com/CCOSTAN/Home-AssistantConfig/blob/master/config/packages/alarm.yaml#L246-L258

All of a sudden `{{ trigger.to_state.attributes.friendly_name }}` doesn't render anymore. :(  
`The Main Slider need to be closed. The {{ trigger.to...`

**Comment by thejeffreystone** [comment]
What version are you running? 

I have heard TTS stopped working for people after .115.4 but started working again in .115.6. 

Probably not it, but figured I would throw it out there.

**Comment by thejeffreystone** [comment]
Just tested mine. `{{ trigger.to_state.attributes.friendly_name }}` is rendering over here.

**Comment by CCOSTAN** [comment]
Thanks @thejeffreystone .. I think it is the way I am calling it.. Your `to_state` seems to be outside of the random loops.. I'm gonna try a new way to do it.  But thanks for testing.

**Comment by thejeffreystone** [comment]
Oh. Yea. Should have looked at that. I think I had issues with it when it was part of the random loop. Like the quotes were messing it up or something.

**Comment by CCOSTAN** [comment]
New code block is working now.. Closing.
