### ISSUE TITLE
Test out REPEAT Functions.

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#902]
I want to test this simple repeat function. 

https://www.home-assistant.io/docs/scripts/#repeat-a-group-of-actions

**Comment by CCOSTAN** [comment]
Testing - 504ea6eebfbe682631cf601cd826b0a9f694eddd

**Comment by pinkywafer** [comment]
have a look at https://github.com/pinkywafer/Home-Assistant_Config/blob/master/packages/system/hacs.yaml
the automation has repeat and uses the repeat.index loop variable and uses choose to work out what it's doing.
I got carried away with that one, and it seems to be working ok so far!!

**Comment by CCOSTAN** [comment]
Thanks Jenny.. That's a good example.  I wanted to test whether I could just put a simple number in there though.. and not use the template.. it's weird.. even the documentation show the template but not a simple number..
