### ISSUE TITLE
Extend Wifi Coverage in my house

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#91]
I'm thinking about these maybe.. they are super cheap!

http://amzn.to/2mh20XM

**Comment by CCOSTAN** [comment]
If anyone has suggestions on a wireless solution to cover 3500 sq feet, i'm all ears.

**Comment by cgarwood** [comment]
I'm a huge fan of the Ubiquiti UniFi access points. https://www.ubnt.com/enterprise/#unifi:hardware

I have a first-gen in my house and have never had to power cycle it to restore connectivity and it covers my entire house (~1200 sq ft) plus most of the front and back yard.

**Comment by aamoroso** [comment]
Ditto.  I have the same and also recommend them.  They also allows you to have 4 different VLANs each with a separate SSID.  I have camera, IOT and streaming VLANs on mine along with the main wireless network.  I also have an ubiquity edgerouter X and it is similarly awesome (albeit a little harder to drive than a consumer router)

**Comment by SEJeff** [comment]
Get the Unifi AC Pro. It is legit. Also, Unifi makes enterprise worthy wireless range extenders, but you shouldn't actually need that.

If you have some money to burn, get an [eero](https://eero.com/), but it doesn't work natively with HASS's device tracker yet.

**Comment by CCOSTAN** [comment]
Thanks for all the solid recommendations everyone. Unifi AC Pro will be here tomorrow. Thanks again.

**Comment by aamoroso** [comment]
And if you're using docker at all this works nicely as the Unify Controller: https://hub.docker.com/r/jacobalberty/unifi/

**Comment by CCOSTAN** [comment]
#97

**Comment by CCOSTAN** [comment]
Still have a dead spot in the front of the house.  Need to try to add the powerline adapters to extend coverage to the front.

**Comment by CCOSTAN** [comment]
Re-used an old Trendnet AP I had to extend wireless B/G/N service to a dead spot.  Used Powerline adapters to get IOT speeds to the other side of the house.  Not great but not bad at all.

**Comment by CCOSTAN** [comment]
Pretty Sure I mounted 2 of my Unifi APs in the wrong orientation which is REALLY messing up coverage.  Sucks since I paid to have them installed on the wall rather than the ceiling.. lesson learned. 

Short term fix is to order some new Cables and remount them on the ceiling. 
https://amzn.to/2K25icM
