### ISSUE TITLE
Figure out a way to get expiration of Cert.

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#92]
Love the idea of getting an alert before cert will expire. 

No sure how to get this done with SSLS.com cert. 

https://github.com/eximo84/homeassistant-config/issues/11

**Comment by SEJeff** [comment]
Nagios's [check_http](https://www.barryodonovan.com/2012/10/10/monitoring-ssl-certificate-expiry-dates-with-nagios) plugin natively allows this. You could run it as a script in hass and check the return code. You don't need to install the entire nagios mess, just the plugin.

The [upstream source](https://www.monitoring-plugins.org/doc/man/check_http.html) is here.
