### ISSUE TITLE
Floorplan

### ISSUE THREAD

**Issue by aureliosaraiva** [CCOSTAN/Home-AssistantConfig#922]
How have you been using the floorplan? Is it a panel in the Home Assistant sidebar?

As I understand it, you open the floorplan directly, without the toolbar and sidebar, how do you do that?

**Comment by CCOSTAN** [comment]
I'm not actively using it at the moment.  I have a plan to migrate to complete lovelace #565 

Primarily I am using Voice for most things. 
https://youtu.be/CQMIPRYNMjc
