### ISSUE TITLE
Implementing Floorplan on Hass.io

### ISSUE THREAD

**Issue by misterjtc** [CCOSTAN/Home-AssistantConfig#967]
It looks like floorplan hasn't been updated in a while but you still refer to it as an important part of your ha setup. Are you still using it as is shown in the docs on the floorplan repo?

I tried to implement it but it looks like custom panels are made obsolete with lovelace. Do you have any documentation on how you implemented floorplan with the current state of hass.io?

Thanks in advance.

**Comment by CCOSTAN** [comment]
Hi @misterjtc - I'm not using the Floorplan as described in the Repo anymore.   My plan is to move to full lovelace now. #476 

That said, there is a new version of Floorplan being released soon that I will be looking at.
https://github.com/ExperienceLovelace/ha-floorplan
